### ISSUE TITLE
fix(devops): generate_e2e_coverage_report.py crashes on real Bruno CLI JSON output

### ISSUE THREAD

**Issue by matiaspakua** [matiaspakua/notaire#658]
## Description

Regression introduced by #587, caught by its own first real CI run (on PR #657, which incidentally exercised the `coverage-report` job for the first time since #587 only touched files outside `playwright-e2e.yml`'s path trigger).

`scripts/generate_e2e_coverage_report.py`'s `_bruno_section()` assumed `bruno-results.json` (produced by `@usebruno/cli run --reporter-json`) is a JSON **object** with a top-level `"summary"` key. The real output is a JSON **array**, so the "Business Coverage Report" CI job now fails every run with:

```
AttributeError: 'list' object has no attribute 'get'
  File "scripts/generate_e2e_coverage_report.py", line 67, in _bruno_section
    summary = bruno_data.get("summary")
```

(job log: https://github.com/matiaspakua/notaire/actions/runs/29951941384/job/89035072980)

## Use Case (Caso de Uso)

Same as #587 — CI/DevOps observability infrastructure, not tied to a numbered CU.

## Acceptance Criteria

- [ ] `_bruno_section()` handles the real array-shaped Bruno CLI JSON output without crashing
- [ ] Add a regression test using an array fixture (not just the previously-assumed dict-with-summary shape)
- [ ] Never fabricate numbers if the array's item shape isn't recognized — same "honest > fabricated > crash" principle as the rest of the script
- [ ] Verify against a real CI run (this script's own bug wasn't caught by unit tests alone since the test fixtures encoded the same wrong assumption as the implementation — the fixture needs to be corrected against real data, not just internally consistent)

## Technical Notes

- The real `bruno-results.json` array's exact item shape (does each item have `assertionResults`? a `status` field? something else?) should be captured from the actual failing job's artifact or a fresh CI run's artifact before finalizing the parser, rather than guessed again.
